DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR2(10) PRIMARY KEY,
    P_NAME VARCHAR2(20) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(20)
);

INSERT INTO PRODUCT 
VALUES ('nb_ss7', '»ï¼º³ëÆ®ºÏ', 1570000, '½Ã¸®Áî 7');
INSERT INTO PRODUCT 
VALUES ('nb_ama4', '¸ÆºÏ¿¡¾î', 1200000, 'xcode 4');
INSERT INTO PRODUCT 
VALUES ('pc_ibm', 'ibmPC', 750000, 'windows 8');
commit;